# Docker Compose para Produção - OrçaZenFinanceiro
version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: orcazen_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: orcazenfinanceiro
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-admin123}
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
    networks:
      - orcazen_network

  # FastAPI Backend
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: orcazen_backend
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://admin:admin123@mongodb:27017/orcazenfinanceiro?authSource=admin
      - SECRET_KEY=${SECRET_KEY:-your-super-secret-key-change-this-in-production}
      - EMAIL_ENABLED=true
      - SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - EMAIL_FROM=${EMAIL_FROM}
    ports:
      - "8001:8001"
    depends_on:
      - mongodb
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - orcazen_network

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL:-http://localhost:8001}
    container_name: orcazen_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - orcazen_network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: orcazen_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - orcazen_network

volumes:
  mongodb_data:
    driver: local

networks:
  orcazen_network:
    driver: bridge